//NAVIGATION CONSTANTS
const NAVIGATOR = {
    START_FLOW: 'START_FLOW',
    LOGIN_FLOW: 'LOGIN_FLOW',
    LANDING_FLOW: 'LANDING_FLOW'
};
const LOGIN_STACK = {
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    PASSWORD_RECOVERY_SCREEN: 'PASSWORD_RECOVERY_SCREEN',
    CODE_VERIFICATION_SCREEN: 'CODE_VERIFICATION_SCREEN'
};
const LANDING_STACK = {
    CASOS_SCREEN: 'CASOS_SCREEN',
    HISTORIAL_SCREEN: 'HISTORIAL_SCREEN'
};
const TAB = {
    CASOS: 'TAB_CASOS',
    HISTORIAL: 'TAB_HISTORIAL',
    ADD: 'TAB_ADD'
};
export {
    NAVIGATOR,
    LOGIN_STACK,
    LANDING_STACK,
    TAB
}